### ISSUE TITLE
Extension don't work for me on Firefox

### ISSUE THREAD

**Issue by 1ns0lvable** [zdhenard42/SOC-Multitool#11]
Hello,

After installing the extension on Firefox 121.0.1, SOC Multitool did not appear in the drop-down menu after right-clicking.

When I tried to load the module in temporary extension mode, I got the following error: "background.service_worker is currently disabled".

I think it's because of this part which is not "compatible" with Firefox :
	"background": {
        "service_worker": "eventPage.js"
    },

So I modified it according to the https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background prerequisites:
	"background": {
		"scripts": ["eventPage.js"],
        "service_worker": "eventPage.js"
    },

And after that, SOC Multitool appear in the drop-down menu after right-clicking.

**Comment by zdhenard42** [comment]
Okay, thank you for this fix! If you want to create a pull request with this fix, I will accept it so that you get credit!
