### ISSUE TITLE
Add Firefox support

### ISSUE THREAD

**Issue by zaee-k** [zdhenard42/SOC-Multitool#8]
As in the title, any plans to implement this for Firefox browser?

**Comment by sebdufourcq** [comment]
Hello,
I've done a port to Firefox but the Manifest V3 implementation is quite different between Chrome and Firefox.
A unique repository will force to mantain at least 2 different "manifest.json".
"browser-polyfill.js" may help to keep one version for the other files but a code refactor is needed.
https://github.com/sebdufourcq/SOC-Multitool-for-Firefox

**Comment by sebdufourcq** [comment]
Actually, it was easier than expected:
Pull request: #9

**Comment by zdhenard42** [comment]
Thank you for being patient with me. I have been tied up with other projects but I will review his pull request over the next few days and provide an update/acceptance. Awesome work creating compatibility with Firefox!
